apiVersion: batch/v1
kind: Job
metadata:
  name: esrall-esrall-esrallytest4
 
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 30
  template:
     

    spec:
      containers:
      - name: esrally
        image: elastic/rally
        # securityContext:
        #   runAsUser: 1000
        #   runAsGroup: 1000
          
        resources:
            limits:
              cpu: 100m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
        command:
        - sh
        - -c
        - |
          export RALLY_HOME="/mnt/rally"
          export CLIENT_OPTIONS="use_ssl:false,verify_certs:false"
          esrally race --track-path=/mnt/mapping --target-hosts=http://elasticsearch-service:9200 --pipeline=benchmark-only --client-options=$CLIENT_OPTIONS
          exit 0;
        volumeMounts:
        - name: rally-benchmarks
          mountPath: "/mnt"
      volumes:
      - name: rally-benchmarks
        persistentVolumeClaim:
          claimName: job-pvc
      restartPolicy: Never