apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
data:
  default.conf: |
    server {
      
      listen 8080;
      server_name nginx2.local;
      location / {
        return 301 https://prod.kb.gcp.elastic-cloud.com;
      }
    }